eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    registerWithEureka: false
    fetchRegistry: true
      
spring:
 application:
    name: newz-nexflix-zuul-api-gateway
server:
  port: 8765
  
ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    authenticationService:
      path: /authenticationService/**
      serviceId: AUTHENTICATION-SERVICE
      
      url: http://localhost:8082
    newsService:
      url: http://localhost:8081
    newsSourceService:
      url: http://localhost:8083
    userProfileService:
      url: http://localhost:8084