#spring:
#  application:
#    name: newsService
#  data:
#   mongodb:
#     database: news
#     port: 27017
#     host: localhost
#server:
# port: 8081
 

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
    
spring:
 data:
   mongodb:
     username: ${MONGO_USER}
     password: ${MONGO_PASSWORD}
     database: ${MONGO_DATABASE}
     port: ${MONGO_PORT}
     host: ${MONGO_HOST}
server:
 port: 8082
 
logging:
  level:
    org:
      mongodb:
        driver: ERROR